spring:
  datasource:
    url: jdbc:mysql://192.168.50.22:3306/longyah_blog?useUnicode=true&characterEncoding=utf8
    username: longyah
    password: longyah.com
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
server:
  servlet:
    context-path: /api
app:
  security:
    password-expire-days: 90
    jwt-token-header: Longyah-Token
    jwt-secret: longyah.com
    jwt-token-expire-seconds: 1440